version: 3

tasks:
  setup:
    cmds:
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  download-data:
    cmds:
      - wget -P data/FashionMNIST/raw https://github.com/zalandoresearch/fashion-mnist/raw/master/data/fashion/train-images-idx3-ubyte.gz
      - wget -P data/FashionMNIST/raw https://github.com/zalandoresearch/fashion-mnist/raw/master/data/fashion/t10k-images-idx3-ubyte.gz
      - wget -P data/FashionMNIST/raw https://github.com/zalandoresearch/fashion-mnist/raw/master/data/fashion/train-labels-idx1-ubyte.gz
      - wget -P data/FashionMNIST/raw https://github.com/zalandoresearch/fashion-mnist/raw/master/data/fashion/t10k-labels-idx1-ubyte.gz